/*
 * Questions imported from the uploaded file: test 2.docx
 * Includes all 19 numbered questions and each 'Please mention' prompt.
 */
window.QUESTIONS = [
  "Section 1. Role and Answering Perspective\n\nWhat is your main role or function in the ED?\n\nPlease mention: Your role, such as charge nurse, triage nurse, zone/floor nurse, resus/trauma nurse, LPN, NP, physician/MD, CTA, ward clerk, unit aide, EVS/housekeeping, EMHAS team, social worker, pharmacist, RT, security, admin, or other.",
  "Section 1. Role and Answering Perspective\n\nWhich shifts or operating conditions are you most familiar with?\n\nPlease mention: Day, evening, night, weekend, high-volume periods, respiratory season, Code Census conditions, or mixed experience.",
  "Section 2. Your Own Role Workflow and Task Ownership\n\nCould you walk me through your workflow during a typical shift, from the beginning of your shift to the end?\n\nPlease mention: What you usually do first, what comes next, what triggers each task, who gives you information, who you communicate with, what information you receive or pass on, and where the workflow usually slows down.",
  "Section 2. Your Own Role Workflow and Task Ownership\n\nHow does your workflow change under different operating conditions?\n\nPlease mention: Compare different shifts, weekends/holidays, busy periods, respiratory season, high isolation demand, and Code Census conditions. Mention what changes, why it changes, and how it affects patient flow, staff workload, room use, handoffs, communication, documentation, cleaning/room turnover, consults, diagnostics, or discharge/admission.",
  "Section 2. Your Own Role Workflow and Task Ownership\n\nWhat task usually takes the most time in your role?\n\nPlease mention: The task name, why it takes time, whether it is patient care, documentation, searching, communication, waiting, room-related work, system-related work, or coordination.",
  "Section 2. Your Own Role Workflow and Task Ownership\n\nWhich tasks are shared between your role and another role?\n\nPlease mention: Shared tasks, the other role(s), how staff decide who does the task, and whether any informal support happens outside the formal role.",
  "Section 2. Your Own Role Workflow and Task Ownership\n\nAre there tasks that change owner depending on shift, staffing, or workload?\n\nPlease mention: Task name, usual owner, alternate owner, and when the change happens.",
  "Section 2. Your Own Role Workflow and Task Ownership\n\nWhich patient groups or pathways does your role interact with most often?\n\nPlease mention: Low-acuity/LAT-eligible, moderate-acuity, high-acuity, ambulance arrivals, trauma/resus, mental health/EMHAS, infectious/isolation, results-pending, admitted/boarding, discharge, transfer, or mixed pathways.",
  "Section 3. Handoffs, Communication, and Information Flow\n\nWho do you usually receive information or tasks from, and who do you usually pass information or tasks to?\n\nPlease mention: The role or team, what information or responsibility is transferred, when it happens, and whether it happens at arrival, triage, rooming, assessment, diagnostics, consult, admission, discharge, transfer, or shift change.",
  "Section 3. Handoffs, Communication, and Information Flow\n\nWhere do handoffs or communication gaps slow down your workflow?\n\nPlease mention: The handoff point, what information is missing or delayed, how the communication happens, who is affected, and whether the gap creates waiting, rework, safety concerns, duplicate communication, or unclear next steps.",
  "Section 4. Systems, Documentation, and Tracking Tools\n\nWhich systems, tools, or documentation steps are part of your workflow?\n\nPlease mention: OPOR/CIS, patient tracking tools, paper forms, whiteboards, phones, pagers, secure messaging, admission/transfer forms, registration tools, room-status tools, or other tools used to know where patients are and what needs to happen next.",
  "Section 4. Systems, Documentation, and Tracking Tools\n\nDo any systems, tools, or documentation steps create delay, duplicate work, or missing information?\n\nPlease mention: The specific system or document, the step affected, whether the issue is delayed updates, duplicate documentation, unclear patient location, unclear room status, difficult information access, or extra communication.",
  "Section 5. Bottlenecks and Slowdown Points\n\nIn your own workflow, where do things most often slow down?\n\nPlease mention: Say where the slowdown happens, the reason, how often it happens, and what happens next. Examples: waiting for triage, room, diagnostic results, consult, admission bed, discharge paperwork, room cleaning, patient movement, documentation, communication, or supplies.",
  "Section 5. Bottlenecks and Slowdown Points\n\nWhich slowdown has the biggest effect on patient flow and on staff workload?\n\nPlease mention: Name one main bottleneck and explain why it has the strongest impact on both patient flow and staff workflow.",
  "Section 6. Space, Room Readiness, and Physical Layout\n\nHow does room availability affect your workflow?\n\nPlease mention: When room availability matters, what happens when no room is available, and which patient groups are most affected.",
  "Section 6. Space, Room Readiness, and Physical Layout\n\nAre there areas where patients wait because the right space is not available?\n\nPlease mention: Waiting room, sub-waiting, results pending, isolation, resus/trauma, EMHAS-related space, admitted/boarding space, treatment room, or other space.",
  "Section 6. Space, Room Readiness, and Physical Layout\n\nAre there layout issues that create extra movement or searching?\n\nPlease mention: Walking distance, supply location, room visibility, staff station location, equipment location, patient location visibility, communication distance, or searching for people/supplies/equipment.",
  "Section 6. Space, Room Readiness, and Physical Layout\n\nWhat should be considered for the new ED space from your workflow perspective?\n\nPlease mention: Space, visibility, room function, results-pending, infection control, communication, staff station, supply access, room turnover, patient/family movement, or safety.",
  "Section 7. Improvement Priorities and Process Map Validation\n\nIf you could improve one part of your role’s workflow, what would it be?\n\nPlease mention: One specific workflow step, why it should be improved, and whether it is a quick fix, a process change, a technology/documentation issue, a staffing issue, or a space/layout issue."
];
